more sure do_stop
git-svn-id: file:///svn/nsd/trunk@2866 a26ef69c-88ff-0310-839f-98b793d9c207

diff --git a/nsdc.sh.in b/nsdc.sh.in
--- a/nsdc.sh.in
+++ b/nsdc.sh.in
@@ -178,7 +178,23 @@ do_start() {
 }
 
 do_stop() {
-	signal "TERM"
+	i=1
+	while test $i -ne 0; do
+		signal "TERM"
+		if test $? -eq 0; then
+			i=0
+		else
+			i=$i+1
+		fi
+
+		if test $i -ge 50; then
+			echo "nsdc stop failed."
+			i=0
+		fi		
+		if test $i -ge 25; then
+			sleep 1
+		fi
+	done
 }
 
 do_reload() {
