If nsdc detects that nsd does not start it will print an error and exit.
git-svn-id: file:///svn/nsd/trunk@2550 a26ef69c-88ff-0310-839f-98b793d9c207

diff --git a/nsdc.sh.in b/nsdc.sh.in
--- a/nsdc.sh.in
+++ b/nsdc.sh.in
@@ -142,7 +142,12 @@ unlock() {
 }
 
 do_start() {
-[ -x ${sbindir}/nsd ] && ${sbindir}/nsd -c ${configfile} 
+	if test -x ${sbindir}/nsd; then
+		${sbindir}/nsd -c ${configfile}
+		test $? = 0 || (echo "nsd startup failed."; exit 1)
+	else
+		echo "${sbindir}/nsd not an executable file, nsd startup failed."; exit 1
+	fi
 }
 
 do_stop() {
