add off-by-one test update branch with trunk bugfixes wouter code review
git-svn-id: file:///svn/nsd/branches/NSD_3_2@2871 a26ef69c-88ff-0310-839f-98b793d9c207

diff --git a/nsdc.sh.in b/nsdc.sh.in
--- a/nsdc.sh.in
+++ b/nsdc.sh.in
@@ -177,6 +177,51 @@ do_start() {
 	fi
 }
 
+controlled_sleep() {
+	if [ $1 -ge 25 ]; then
+		sleep 1
+	fi
+}
+
+controlled_stop() {
+	pid=$1
+	try=1
+
+	while [ $try -ne 0 ]; do
+		if [ ${try} -gt 50 ]; then
+			echo "nsdc stop failed"
+			return 1
+		else
+			if [ $try -eq 1 ]; then
+				kill -TERM ${pid}
+			else
+				kill -TERM ${pid} &>/dev/null
+			fi
+
+			# really stopped?
+			kill -0 ${pid} &>/dev/null 
+			if [ $? -eq 0 ]; then
+				controlled_sleep ${try}
+				try=`expr ${try} + 1`
+			else
+				try=0
+			fi
+		fi
+	done
+
+	return 0
+}
+
+do_controlled_stop() {
+	if [ -s ${pidfile} ]; then
+		pid=`cat ${pidfile}`
+		controlled_stop ${pid} && return 0
+	else
+		echo "nsd is not running"
+	fi
+	return 1
+}
+
 do_stop() {
 	signal "TERM"
 }
@@ -383,8 +428,7 @@ notify)
 	done
 	;;
 restart)
-	do_stop && sleep 1
-	do_start
+	do_controlled_stop && do_start
 	;;
 *)
 	usage
