For coss platform build, debug config.log output.

diff --git a/.github/workflows/analysis_ports.yml b/.github/workflows/analysis_ports.yml
--- a/.github/workflows/analysis_ports.yml
+++ b/.github/workflows/analysis_ports.yml
@@ -73,7 +73,8 @@ jobs:
             autoconf && autoheader
             (cd simdzone && autoconf && autoheader)
             libtoolize -c -i || glibtoolize -c -i
-            ./configure ${{ matrix.cross_platform_config }}
+            ./configure ${{ matrix.cross_platform_config }} || cat config.log
+            echo "debug fail"; exit 1
             echo "::endgroup::"
             echo "::group::make"
             make -j2
